<a href="https://colab.research.google.com/github/smoscoso/Conexi-n_DB/blob/main/Conexi%C3%B3n_Base_de_Datos_Clase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import mysql.connector

def conectar():
    """
    Establece una conexión con la base de datos MySQL.

    Conecta a la base de datos `employees` utilizando las credenciales y parámetros de conexión especificados.
    Devuelve un objeto de conexión a la base de datos si tiene éxito, de lo contrario devuelve `None`.

    Returns:
        mydb (mysql.connector.connection.MySQLConnection): Objeto de conexión a la base de datos.
        None: Si ocurre un error durante la conexión.
    """
    try:
        mydb = mysql.connector.connect(
            host="18.116.82.240",
            user="studentsucundi",
            passwd="mami_prende_la_radi0",
            port="3306",
            database="employees"
        )
        return mydb
    except mysql.connector.Error as error:
        print("Error al conectar con la base de datos", error)
        return None

# Establece la conexión a la base de datos
mydb = conectar()

def modificar_tabla(accion, nombre_comlumna=None, tipo_dato=None, nuevo_nombre=None):
    """
    Modifica la estructura de la tabla `employees` según la acción especificada.

    Realiza operaciones de agregar, eliminar, renombrar o modificar columnas en la tabla `employees`.

    Args:
        accion (str): Acción a realizar (agregar, eliminar, renombrar, modificar).
        nombre_comlumna (str, opcional): Nombre de la columna a modificar. Requerido para agregar, eliminar, renombrar y modificar.
        tipo_dato (str, opcional): Tipo de dato de la columna. Requerido para agregar, renombrar y modificar.
        nuevo_nombre (str, opcional): Nuevo nombre de la columna. Requerido para renombrar.

    Returns:
        None
    """
    if mydb is not None:
        try:
            cursor = mydb.cursor()

            if accion == "agregar":
                cursor.execute(f"ALTER TABLE employees ADD {nombre_comlumna} {tipo_dato}")
            elif accion == "eliminar":
                cursor.execute(f"ALTER TABLE employees DROP COLUMN {nombre_comlumna}")
            elif accion == "renombrar":
                cursor.execute(f"ALTER TABLE employees CHANGE {nombre_comlumna} {nuevo_nombre} {tipo_dato}")
            elif accion == "modificar":
                cursor.execute(f"ALTER TABLE employees MODIFY {nombre_comlumna} {tipo_dato}")
            else:
                print("Acción no válida. Use 'agregar', 'eliminar', 'modificar' o 'renombrar'.")
                return

            # Confirmar los cambios en la base de datos
            mydb.commit()
        except mysql.connector.Error as error:
            print("Error al modificar la tabla", error)
        finally:
            cursor.close()

def Crear_Empleado(num_Empl, fecha_Cumpl, nombre, apellido, genero, fecha_Contr, email):
    """
    Crea un nuevo registro de empleado en la tabla `employees`.

    Inserta un nuevo empleado con los datos especificados.

    Args:
        num_Empl (int): Número de empleado.
        fecha_Cumpl (str): Fecha de cumpleaños del empleado.
        nombre (str): Nombre del empleado.
        apellido (str): Apellido del empleado.
        genero (str): Género del empleado.
        fecha_Contr (str): Fecha de contratación del empleado.
        email (str): Correo electrónico del empleado.

    Returns:
        None
    """
    if mydb is not None:
        try:
            cursor = mydb.cursor()
            cursor.execute(
                "INSERT INTO employees (num_Empleado, fecha_Cumpl, nombre, apellido, genero, fecha_Contr, email) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                (num_Empl, fecha_Cumpl, nombre, apellido, genero, fecha_Contr, email)
            )
            mydb.commit()
            print(f"El empleado {nombre} {apellido} fue creado con éxito.")
        except mysql.connector.Error as error:
            print("Error al crear el empleado", error)
        finally:
            cursor.close()

def Leer_Empleado():
    """
    Lee y muestra todos los registros de empleados en la tabla `employees`.

    Recupera y muestra todos los registros de la tabla `employees`.

    Returns:
        None
    """
    if mydb:
        try:
            cursor = mydb.cursor()
            cursor.execute("SELECT * FROM employees")
            empleados = cursor.fetchall()
            for empleado in empleados:
                print(empleado)
        except mysql.connector.Error as error:
            print("Error al leer los empleados", error)
        finally:
            cursor.close()

def actualizar_empleado(id_empleado, nombre=None, apellido=None, trabajo=None, salario=None):
    """
    Actualiza la información de un empleado existente en la tabla `employees`.

    Permite actualizar el nombre, apellido, trabajo y salario de un empleado especificado por su ID.

    Args:
        id_empleado (int): ID del empleado a actualizar.
        nombre (str, opcional): Nuevo nombre del empleado.
        apellido (str, opcional): Nuevo apellido del empleado.
        trabajo (str, opcional): Nuevo trabajo del empleado.
        salario (float, opcional): Nuevo salario del empleado.

    Returns:
        None
    """
    mydb = conectar()
    if mydb is not None:
        try:
            cursor = mydb.cursor()
            sql = "UPDATE employees SET "
            valores = []

            if nombre:
                sql += "nombre = %s, "
                valores.append(nombre)
            if apellido:
                sql += "apellido = %s, "
                valores.append(apellido)
            if trabajo:
                sql += "trabajo = %s, "
                valores.append(trabajo)
            if salario:
                sql += "salario = %s, "
                valores.append(salario)

            # Remover la última coma y espacio
            sql = sql.rstrip(", ")
            sql += " WHERE id = %s"
            valores.append(id_empleado)

            cursor.execute(sql, tuple(valores))
            mydb.commit()
            print(f"Empleado con ID {id_empleado} actualizado exitosamente.")
        except mysql.connector.Error as error:
            print("Error al actualizar el empleado:", error)
        finally:
            cursor.close()